import { Scalekit } from "@scalekit-sdk/node";
import type { NextFunction, Request, Response } from "express";

// ---------------------------------------------------------------------------
// Scalekit client (lazy-initialized so stdio mode never touches these vars)
// ---------------------------------------------------------------------------

let _scalekit: Scalekit | null = null;

function getScalekitClient(): Scalekit {
  if (_scalekit) return _scalekit;

  const envUrl = process.env.SCALEKIT_ENVIRONMENT_URL;
  const clientId = process.env.SCALEKIT_CLIENT_ID;
  const clientSecret = process.env.SCALEKIT_CLIENT_SECRET;

  if (!envUrl || !clientId || !clientSecret) {
    throw new Error(
      "OAuth is enabled but Scalekit credentials are missing. " +
        "Set SCALEKIT_ENVIRONMENT_URL, SCALEKIT_CLIENT_ID, and SCALEKIT_CLIENT_SECRET."
    );
  }

  _scalekit = new Scalekit(envUrl, clientId, clientSecret);
  return _scalekit;
}

// ---------------------------------------------------------------------------
// OAuth resource metadata
// ---------------------------------------------------------------------------

/**
 * The resource identifier for this MCP server.
 * Falls back to the autogenerated resource_id from the Scalekit dashboard if
 * MCP_SERVER_URL is not set.
 */
export function getResourceId(): string {
  return process.env.MCP_SERVER_URL ?? process.env.SCALEKIT_RESOURCE_ID ?? "";
}

export function getMetadataEndpoint(): string {
  const base = process.env.MCP_SERVER_URL ?? "";
  return `${base}/.well-known/oauth-protected-resource`;
}

/** Scopes advertised by this MCP server (comma-separated env var). */
export function getScopesSupported(): string[] {
  return (process.env.MCP_SCOPES ?? "meta_ads:read").split(",").map((s) => s.trim());
}

/** Build the OAuth Protected Resource Metadata document (RFC 9728). */
export function buildResourceMetadata() {
  const envUrl = process.env.SCALEKIT_ENVIRONMENT_URL ?? "";
  const resourceId = getResourceId();
  const scaleKitResourceId = process.env.SCALEKIT_RESOURCE_ID ?? resourceId;

  return {
    resource: resourceId,
    authorization_servers: [`${envUrl}/resources/${scaleKitResourceId}`],
    bearer_methods_supported: ["header"],
    resource_documentation: `${resourceId}/docs`,
    scopes_supported: getScopesSupported(),
  };
}

// ---------------------------------------------------------------------------
// WWW-Authenticate header helpers
// ---------------------------------------------------------------------------

export const WWWHeader = {
  key: "WWW-Authenticate",
  value: () =>
    `Bearer realm="OAuth", resource_metadata="${getMetadataEndpoint()}"`,
};

// ---------------------------------------------------------------------------
// Express middleware
// ---------------------------------------------------------------------------

/**
 * Auth middleware for the HTTP MCP server.
 *
 * - Bypasses `.well-known` paths (public discovery endpoints).
 * - Extracts and validates the Bearer JWT issued by Scalekit.
 * - Returns 401 with a proper WWW-Authenticate header on failure.
 *
 * Enabled only when OAUTH_ENABLED=true; otherwise passes through (useful for
 * local development or stdio mode).
 */
export async function authMiddleware(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  // Allow public discovery + health check without auth
  if (req.path.includes(".well-known") || req.path === "/health") {
    return next();
  }

  try {
    const authHeader = req.headers["authorization"];
    const token =
      authHeader?.startsWith("Bearer ") ? authHeader.slice(7).trim() : null;

    if (!token) {
      res.status(401).set(WWWHeader.key, WWWHeader.value()).end();
      return;
    }

    const resourceId = getResourceId();
    const scalekit = getScalekitClient();

    await scalekit.validateToken(token, {
      audience: resourceId ? [resourceId] : undefined,
    });

    next();
  } catch {
    res.status(401).set(WWWHeader.key, WWWHeader.value()).end();
  }
}

/**
 * Scope-checking helper for individual tools that need finer-grained control.
 *
 * Usage:
 *   await requireScope(req, res, "meta_ads:write");
 *   // returns false and sends 403 if scope is missing
 */
export async function requireScope(
  req: Request,
  res: Response,
  scope: string
): Promise<boolean> {
  const authHeader = req.headers["authorization"];
  const token =
    authHeader?.startsWith("Bearer ") ? authHeader.slice(7).trim() : null;

  if (!token) {
    res.status(401).set(WWWHeader.key, WWWHeader.value()).end();
    return false;
  }

  try {
    const resourceId = getResourceId();
    const scalekit = getScalekitClient();
    await scalekit.validateToken(token, {
      audience: resourceId ? [resourceId] : undefined,
      requiredScopes: [scope],
    });
    return true;
  } catch {
    res.status(403).json({
      error: "insufficient_scope",
      error_description: `Required scope: ${scope}`,
      scope,
    });
    return false;
  }
}
